version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/var/lib/grafana/plugins/dark-sky
      - ./provisioning/datatsources:/etc/grafana/provisioning/datasources